name: Deploy Cloud Resume Challenge Website to S3

run-name: ${{ github.actor }} is deploying changes made to CRC Website ğŸš€

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "./github_actions_scripts/*"
      - ".git/*"

env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }} 
  DISTRIBUTION_ID: ${{secrets.DISTRIBUTION_ID}}

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # required for requesting the JWT
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Set script permissions
        run:  |
          chmod u+x ./github_actions_scripts/sync_s3_and_invalidate_cloudfront.sh
      - name: Sync to S3 and invalidate Cloudfront distribution
        run:  | 
          ./github_actions_scripts/sync_s3_and_invalidate_cloudfront.sh
