name: Deploy Cloud Resume Challenge Website to S3
run-name: ${{ github.actor }} is deploying changes made to CRC Website ðŸš€
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout
      id-token: write # required for requesting the JWT
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Sync to S3
        id: sync_s3
        run:  |
          echo "$(aws s3 sync . s3://${{ secrets.BUCKET_NAME }} \
            --size-only \
            --delete \
            --exclude '.git/*' \
            --exclude '.github/*' \
            --exclude 'README.md' \
            --exclude '.gitignore')\n" >> $GITHUB_OUTPUT
      - name: Invalidate CloudFront distribution
        run:  |
          aws cloudfront create-invalidation \
            --distribution-id ${{secrets.DISTRIBUTION_ID}} \
            --paths
